services:
  web_app_db:
    restart: always
    container_name: web-app-db
    image: mysql:8.0
    env_file:
      - .env
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_NAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5

  django_backend:
    container_name: django-backend
    build:
      context: .
      dockerfile: DockerFile
    env_file:
      - .env
    entrypoint: /entrypoint.sh
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/django_project
    depends_on:
      web_app_db:
        condition: service_healthy
    restart: on-failure

  test:
    build:
      context: .
      dockerfile: DockerFile
    env_file:
      - .env
    entrypoint: /entrypoint.sh
    command: bash -c "python manage.py test api.products"
    volumes:
      - .:/django_project
    depends_on:
      web_app_db:
        condition: service_healthy
