# Generated by Django 3.0.11 on 2025-03-28 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="카테고리명")),
            ],
            options={
                "verbose_name": "카테고리",
                "verbose_name_plural": "카테고리 목록",
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="쿠폰 코드"
                    ),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="할인율"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
            ],
            options={
                "verbose_name": "쿠폰",
                "verbose_name_plural": "쿠폰 목록",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="상품명")),
                ("description", models.TextField(verbose_name="상품 설명")),
                ("price", models.PositiveIntegerField(verbose_name="가격(원)")),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="할인율"
                    ),
                ),
                (
                    "coupon_applicable",
                    models.BooleanField(
                        default=False, verbose_name="쿠폰 적용 가능 여부"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.Category",
                        verbose_name="카테고리",
                    ),
                ),
            ],
            options={
                "verbose_name": "상품",
                "verbose_name_plural": "상품 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
