# Generated by Django 3.0.11 on 2025-03-29 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="coupon",
            options={"verbose_name": "coupon", "verbose_name_plural": "coupons"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
        ),
    ]
